### PR TITLE
hem-7155t support added

### PR DESCRIPTION
**Pull request by dromie**
I've added preliminary support for hem-7155T, tested with HEM-7155T-EBK

2023-03-25 19:48:21,378 - omblepy - INFO - Attempt to import module for device hem-7155t
2023-03-25 19:48:21,405 - omblepy - INFO - Attempt connecting to 00:5F:BF:0F:00:26.
2023-03-25 19:48:26,792 - omblepy - INFO - communication started
2023-03-25 19:48:28,043 - omblepy - INFO - start reading data, this can take a while, use debug flag to see progress
2023-03-25 19:48:47,342 - omblepy - INFO - communication finished
2023-03-25 19:48:47,346 - omblepy - INFO - writing data to user1.csv
2023-03-25 19:48:47,347 - omblepy - INFO - writing data to user2.csv
2023-03-25 19:48:47,348 - omblepy - INFO - unpair and disconnect
Traceback (most recent call last):
  File "omblepy.py", line 397, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "omblepy.py", line 395, in main
    await bleClient.disconnect()
  File "/home/gnandor/git/private/omblepy/venv/lib/python3.8/site-packages/bleak/__init__.py", line 540, in disconnect
    return await self._backend.disconnect()
  File "/home/gnandor/git/private/omblepy/venv/lib/python3.8/site-packages/bleak/backends/bluezdbus/client.py", line 413, in disconnect
    assert self._bus is None
AssertionError

Since I don't have any other devices, I don't know if this assertion failure is "normal". If you have any idea how to debug this, I'm open for some development. (Ubuntu 20.04.6, Intel Corporation Wi-Fi 6 AX200)

Timesync is not yet tested.

### CODE REVIEW

**Comment by dromie** [comment]
No additional modification was required for timesync, works fine.

2023-03-25 20:17:14,357 - omblepy - INFO - device is set to date: 2023-03-25 20:11:54
2023-03-25 20:17:14,358 - omblepy - INFO - settings updated to new date 2023-03-25 20:17:14
2023-03-25 20:17:14,358 - omblepy - DEBUG - write to 0x80 size 0x10
2023-03-25 20:17:14,358 - omblepy - DEBUG - tx ch0 > 1801c0008010c8a80000000000001703
2023-03-25 20:17:14,359 - omblepy - DEBUG - tx ch1 > 1914110ed60000f9
2023-03-25 20:17:14,474 - omblepy - DEBUG - rx ch0 < 1881c0008010c8a80000000000001703
2023-03-25 20:17:14,475 - omblepy - DEBUG - rx ch1 < 1914110ed60000790000000000000000
2023-03-25 20:17:14,562 - omblepy - DEBUG - tx ch0 > 080f000000000007
2023-03-25 20:17:14,684 - omblepy - DEBUG - rx ch0 < 088f0000000000870000000000000000

**Comment by userx14** [comment]
Hi @dromie,

thank you for testing and adding support for the HEM-7155T.
Your PR looks good and I'll add the device to the "supported devices" table in the readme.

> Since I don't have any other devices, I don't know if this assertion failure is "normal".

As far as I know it's normal on linux, and did not cause any problems for me.
It could be that depending on the os, calling disconnect after unpair is not allowed, but I'm not sure.
I've added this part, because on windows a second connection with the device was impossible.
https://github.com/userx14/omblepy/blob/0dddc074ec3bc7b05cb4e9aabee03ed4322432ee/omblepy.py#L366-L367

Best,
Benjamin

**Comment by userx14** [comment]
Well I forgot to ask, did you test if reading and writing the record counter works (-n option)?

**Comment by dromie** [comment]
I forgot to test it yesterday, but done it today. works fine:

first run:

python3 omblepy.py -d HEM-7155T  -m 00:5F:BF:0F:00:26 -n
2023-03-26 09:33:26,867 - omblepy - INFO - Attempt to import module for device hem-7155t
2023-03-26 09:33:26,892 - omblepy - INFO - Attempt connecting to 00:5F:BF:0F:00:26.
2023-03-26 09:33:30,458 - omblepy - INFO - communication started
2023-03-26 09:33:31,461 - omblepy - INFO - Current ring buffer slot user1: 5.
2023-03-26 09:33:31,461 - omblepy - INFO - Unread records user1: 5.
2023-03-26 09:33:31,461 - omblepy - INFO - Current ring buffer slot user2: 3.
2023-03-26 09:33:31,461 - omblepy - INFO - Unread records user2: 3.
2023-03-26 09:33:31,461 - omblepy - INFO - start reading data, this can take a while, use debug flag to see progress
2023-03-26 09:33:33,096 - omblepy - INFO - communication finished
2023-03-26 09:33:33,100 - omblepy - INFO - writing data to user1.csv
2023-03-26 09:33:33,101 - omblepy - INFO - writing data to user2.csv
2023-03-26 09:33:33,103 - omblepy - INFO - unpair and disconnect

second run:
python3 omblepy.py -d HEM-7155T  -m 00:5F:BF:0F:00:26 -n
2023-03-26 09:33:56,376 - omblepy - INFO - Attempt to import module for device hem-7155t
2023-03-26 09:33:56,402 - omblepy - INFO - Attempt connecting to 00:5F:BF:0F:00:26.
2023-03-26 09:34:01,947 - omblepy - INFO - communication started
2023-03-26 09:34:03,171 - omblepy - INFO - Current ring buffer slot user1: 5.
2023-03-26 09:34:03,171 - omblepy - INFO - Unread records user1: 0.
2023-03-26 09:34:03,172 - omblepy - INFO - Current ring buffer slot user2: 3.
2023-03-26 09:34:03,172 - omblepy - INFO - Unread records user2: 0.
2023-03-26 09:34:03,172 - omblepy - INFO - start reading data, this can take a while, use debug flag to see progress
2023-03-26 09:34:03,486 - omblepy - INFO - communication finished
2023-03-26 09:34:03,491 - omblepy - INFO - writing data to user1.csv
2023-03-26 09:34:03,492 - omblepy - INFO - writing data to user2.csv
2023-03-26 09:34:03,493 - omblepy - INFO - unpair and disconnect

**Pull request merged**
